# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{  'Star Wars' }, {  'Lord of the Rings' }])
#   Character.create( 'Luke', movie: movies.first)

User.destroy_all 
Song.destroy_all
Artist.destroy_all
SongArtist.destroy_all
Review.destroy_all



u1 = User.create(user_name:"patricia", password:"yeet")
u2 = User.create(user_name:"max", password:"cheese")
u3 = User.create(user_name:"alexa", password:"avacado")
u4 = User.create(user_name:"yeet", password:"yoted")

s1 = Song.create(genre:"Country", title:"Ring of Fire", length:"2:38",spotify:"https://open.spotify.com/embed/track/6YffUZJ2R06kyxyK6onezL?si=jn25vbbvT5SwjHP8ysJHMg")
s2 = Song.create(genre:"Hip-hop", title:"Red Roses", length:"4:22",spotify:"https://open.spotify.com/embed/track/3ZhTT6yjZwpPph5MIJ53XY?si=ABeLR3tuTYW9czRz_Jl2Og")
s3 = Song.create(genre:"Old", title:"Fly me to the moon", length:"2:26",spotify:"https://open.spotify.com/embed/track/2dR5WkrpwylTuT3jRWNufa?si=BQfyAmYwTxW0MCfU0uuMVA")
s4 = Song.create(genre:"Hip-hop", title:"going down!", length:"1:55",spotify:"https://open.spotify.com/embed/track/7CkbRn6S0itJqcqn88AtSV?si=kSl1lf_JQ-KeTadWIbslWQ")
s5 = Song.create(genre:"Hip-hop", title:"i", length:"3:02",spotify:"https://open.spotify.com/embed/track/4ZT9FnbFu1PaBfV3itxiqT?si=uskAEXY0TiOsZmED8SuEiA")
s6 = Song.create(genre:"Hip-hop", title:"Fire Burning", length:"4:00",spotify:"https://open.spotify.com/embed/track/2oENJa1T33GJ0w8dC167G4?si=jql-uU4lTZKps3WmzdTMkA")
s7 = Song.create(genre:"Hip-hop", title:"Headlines", length:"3:56",spotify:"https://open.spotify.com/embed/track/6LxSe8YmdPxy095Ux6znaQ?si=6re87ABJSXOrvV7S84Fsbg")
s8 = Song.create(genre:"Hip-hop", title:"Controlla", length:"4:05",spotify:"https://open.spotify.com/embed/track/3O8NlPh2LByMU9lSRSHedm?si=ngQa3DftSf-MpLwxprYNIQ")
s9 = Song.create(genre:"Hip-hop", title:"Best I Ever Had", length:"4:19",spotify:"https://open.spotify.com/embed/track/1GxHeBvQ9935Dd3cSfsfBa?si=xCuMs4R-RHCizMJdArk8pg")
s10 = Song.create(genre:"Hip-hop", title:"Marvin's Room", length:"5:47",spotify:"https://open.spotify.com/embed/track/047fCsbO4NdmwCBn8pcUXl?si=Sc9jlHjJTvm96HyL18aBoQ")
s11 = Song.create(genre:"Hip-hop", title:"Nowadays", length:"3:24",spotify:"https://open.spotify.com/embed/track/2u7mxWSeoqTXndK5e08jMp?si=Y7ABZKgBRNShJ872f3C_Lw")
s12 = Song.create(genre:"Hip-hop", title:"Lucid Dreams", length:"4:00",spotify:"https://open.spotify.com/embed/track/285pBltuF7vW8TeWk8hdRR?si=vmAXIYUuQQCec7Rvny8NOg")
s13 = Song.create(genre:"Hip-hop", title:"The Hills", length:"4:02",spotify:"https://open.spotify.com/embed/track/7fBv7CLKzipRk6EC6TWHOB?si=WOf7ZvOTSR-GnDN-zTA52Q")
s14 = Song.create(genre:"Hip-hop", title:"Adaptation", length:"4:44",spotify:"https://open.spotify.com/embed/track/4pHQ9RYFhn3W0ha5KEuMnj?si=61I1S55YQJy5MADNctNxjw")
s15 = Song.create(genre:"Hip-hop", title:"Can't Feel My Face", length:"3:33",spotify:"https://open.spotify.com/embed/track/22VdIZQfgXJea34mQxlt81?si=zYrRMrCMSTao0_83-SvEyg")
s16 = Song.create(genre:"Pop", title:"Beat it", length:"4:18",spotify:"https://open.spotify.com/embed/track/52xaypL0Kjzk0ngwv3oBPR?si=s3P-55mGRgCx2o_VGS5tPQ")
s17 = Song.create(genre:"Pop", title:"Billie Jean", length:"4:54",spotify:"https://open.spotify.com/embed/track/5ChkMS8OtdzJeqyybCc9R5?si=bAo4GzXQQneQr-znGp-4ww")
s18 = Song.create(genre:"Pop", title:"Smooth Criminal", length:"4:18",spotify:"https://open.spotify.com/embed/track/2GVYPY8Sv7U7cJkDFu3Ft1?si=n1AYYbDvQEiH2pXwqAROMw")
s19 = Song.create(genre:"Pop", title:"Thriller", length:"5:57",spotify:"https://open.spotify.com/embed/track/7azo4rpSUh8nXgtonC6Pkq?si=YRqYmYcES0GoWA8n5xWJsg")
s20 = Song.create(genre:"Pop", title:"PYT", length:"3:59",spotify:"https://open.spotify.com/embed/track/5lA3pwMkBdd24StM90QrNR?si=4REvLO_ERWuGnrTCFhZ-7g")
s21 = Song.create(genre:"Hip-hop", title:"This could be us", length:"3:26",spotify:"https://open.spotify.com/embed/track/4jTiyLlOJVJj3mCr7yfPQD?si=sCzmLbl4ROKTqivH93FjHQ")
s22 = Song.create(genre:"Hip-hop", title:"No Flex Zone", length:"3:51",spotify:"https://open.spotify.com/embed/track/2L8cFPItBljPNJgPjTnuIf?si=BpRO3pHqREqgARBLlVsHag")
s23 = Song.create(genre:"Hip-hop", title:"Come Get Her", length:"3:33",spotify:"https://open.spotify.com/embed/track/1Ser4X0TKttOvo8bgdytTP?si=naUaUByZRHu5DEnAL4qvKg")
s24 = Song.create(genre:"Hip-hop", title:"Throw some mo", length:"4:20",spotify:"https://open.spotify.com/embed/track/5uqphUYsR45kPYplrYSAQh?si=wUtV886pSCuMWo34PzE1yg")
s25 = Song.create(genre:"Hip-hop", title:"Powerglide", length:"5:32",spotify:"https://open.spotify.com/embed/track/1BuZAIO8WZpavWVbbq3Lci?si=Wak3cBJLSaG-P2yJqxDNNQ")
s26 = Song.create(genre:"Hip-hop", title:"Black Beatles", length:"4:52",spotify:"https://open.spotify.com/embed/track/6fujklziTHa8uoM5OQSfIo?si=OKETEHkyRBOrvWWD0sZTrA")
s27 = Song.create(genre:"Hip-hop", title:"Do yoga", length:"3:59",spotify:"https://open.spotify.com/embed/track/0Ic9AMmXhdk7l53KmTqdFO?si=LAy32OpIQDSc-ecEsruXiQ")
s28 = Song.create(genre:"Rock", title:"Africa", length:"4:56",spotify:"https://open.spotify.com/embed/track/2374M0fQpWi3dLnB54qaLX?si=EnreK0QuSceefcDyo_rxRQ")
s29 = Song.create(genre:"Hip-hop", title:"Lust", length:"2:36",spotify:"https://open.spotify.com/embed/track/7oJrVhiTPZGBXWPwhxjy9S?si=97Wg5OdNTFuOawTl6oiDfQ")
s30 = Song.create(genre:"Hip-hop", title:"90210", length:"5:39",spotify:"https://open.spotify.com/embed/track/51EC3I1nQXpec4gDk0mQyP?si=86daRi7PQwW9iT7_WV4vDA")
s31 = Song.create(genre:"Hip-hop", title:"biebs in the trap", length:"3:34",spotify:"https://open.spotify.com/embed/track/0ESJlaM8CE1jRWaNtwSNj8?si=D7DlzN8vTPSk0mVKomby5Q")
s32 = Song.create(genre:"Hip-hop", title:"Antidote", length:"4:22",spotify:"https://open.spotify.com/embed/track/1wHZx0LgzFHyeIZkUydNXq?si=nrsDQ_7fT3-f3I3pZwt6Hg")

a1 = Artist.create(name: "Johnny Cash", artist_url: "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNDc0OTI3NjMw/johnny-cash-9240610-1-402.jpg" ,description:"John R. Cash (born J. R. Cash; February 26, 1932 – September 12, 2003) was an American singer-songwriter, guitarist, actor, and author.He is one of the best-selling music artists of all time, having sold more than 90 million records worldwide. His genre-spanning songs and sound embraced country music, rock and roll, rockabilly, blues, folk, and gospel. This crossover appeal won Cash the rare honor of being inducted into the Country Music, Rock and Roll, and Gospel Music Halls of Fame.")
a2 = Artist.create(name: "Lil Skies", artist_url: "https://i1.sndcdn.com/avatars-000589821045-wrrfig-t500x500.jpg" ,description:"Kimetrius Christopher Foose (born August 4, 1998), known professionally as Lil Skies, is an American rapper, singer and songwriter from Waynesboro, Pennsylvania currently signed to All We Got Entertainment through Atlantic Records.")
a3 = Artist.create(name: "Frank Sinatra", artist_url: "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjg4MTE2MjM4/frank-sinatra-9484810-3-402.jpg" ,description:"Francis Albert Sinatra (/sɪˈnɑːtrə/; December 12, 1915 – May 14, 1998) was an American singer, actor and producer who was one of the most popular and influential musical artists of the 20th century. He is one of the best-selling music artists of all time, having sold more than 150 million records worldwide.")
a4 = Artist.create(name: "XXXTentacion", artist_url: "https://www.rollingstone.com/wp-content/uploads/2018/06/xxxtentacion-legacy-46d1d3ca-6512-453f-817d-d39ac30d3af9.jpg?resize=900,600&w=450" ,description:"Jahseh Dwayne Ricardo Onfroy (January 23, 1998 – June 18, 2018), known professionally as XXXTentacion[a] (/ˌɛksˌɛksˌɛksˌtɛntəˈsjɒn/), was an American rapper, singer and songwriter. Although a controversial figure within the hip hop industry, Onfroy has been regarded to have left behind a huge musical footprint due to his impact on his young fanbase and his popularity during his short career.")
a5 = Artist.create(name: "Drake", artist_url: "https://www.pnglot.com/pngfile/detail/265-2651013_drake-drake-drake-hotline-bling-template.png" ,description:"Aubrey Drake Graham (born October 24, 1986) is a Canadian rapper, singer, songwriter, record producer, actor, and businessman.")
a6 = Artist.create(name: "Sean Kingston", artist_url: "https://timesofindia.indiatimes.com/thumb/msid-66349178,imgsize-48686,width-800,height-600,resizemode-4/66349178.jpg" ,description:"KiSean Paul Anderson (born February 3, 1990), known professionally as Sean Kingston, is a Jamaican-American singer, songwriter, rapper and record producer whose first album, Sean Kingston, was released in 2007.")
a7 = Artist.create(name: "Juice WRLD", artist_url: "https://www.billboard.com/files/styles/article_main_image/public/media/juice-wrld-bonnaroo-2019-billboard-1548.jpg",description:"Jarad A. Higgins (born December 2, 1998), better known by his stage Juice Wrld (pronounced as 'Juice World'), is an American rapper, singer, and songwriter.")
a8 = Artist.create(name: "The Weeknd", artist_url: "https://media.gq.com/photos/586fbf1b1a8ba20b4c0f1881/master/w_2000,h_2666,c_limit/the-weeknd-0217-GQ-FEWE06-01.jpg",description:"Abel Makkonen Tesfaye (born February 16, 1990), better known by his stage The Weeknd, is a Canadian singer, songwriter and record producer.")
a9 = Artist.create(name: "Michael Jackson", artist_url: "https://i.pinimg.com/originals/48/57/1a/48571a16f33504a0b042ceb3b5ed72ac.jpg" ,description:"Michael Joseph Jackson (August 29, 1958 – June 25, 2009) was an American singer, songwriter, and dancer. Dubbed the 'King of Pop', he is regarded as one of the most significant cultural figures of the 20th century and one of the greatest entertainers.")
a10 = Artist.create(name: "Rae Sremmurd", artist_url: "http://www3.pictures.zimbio.com/gi/Rae+Sremmurd+IGA+X+BET+Awards+Party+2018+dVuBcLXb4pMl.jpg",description:"Rae Sremmurd is an American hip hop duo originating from Tupelo, Mississippi formed by two brothers, Slim Jxmmi and Swae Lee.")
a11 = Artist.create(name: "Toto", artist_url: "https://pbs.twimg.com/media/ECQc1xzWwAE2d0-.jpg",description:"Toto was an American rock band formed in 1977 in Los Angeles. The band's most recent lineup consisted of Joseph Williams (lead vocals), David Paich (keyboards, vocals), Steve Porcaro (keyboards), Steve Lukather (guitars, vocals), plus touring members Lenny Castro (percussion), Warren Ham (saxophone), Shem von Schroeck (bass) and Shannon Forrest (drums).")
a12 = Artist.create(name: "Travis Scott", artist_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_gtq1Y76KVkYA6LGPFBKtwU_--7J4WEZ9HR0ANaUGZ2OIba1m",description:"Jacques Berman Webster II (born April 30, 1991), known professionally as Travis Scott (formerly stylized as Travi$ Scott), is an American rapper, singer, songwriter and record producer.")

SongArtist.create(song_id:s1.id, artist_id:a1.id)
SongArtist.create(song_id: s2.id, artist_id: a2.id)
SongArtist.create(song_id: s3.id, artist_id: a3.id)
SongArtist.create(song_id: s4.id, artist_id: a4.id)
SongArtist.create(song_id: s5.id, artist_id: a2.id)
SongArtist.create(song_id: s6.id, artist_id: a6.id)
SongArtist.create(song_id: s7.id, artist_id: a5.id)
SongArtist.create(song_id: s8.id, artist_id: a5.id)
SongArtist.create(song_id: s9.id, artist_id: a5.id)
SongArtist.create(song_id: s10.id, artist_id: a5.id)
SongArtist.create(song_id: s11.id, artist_id: a2.id)
SongArtist.create(song_id: s12.id, artist_id: a7.id)
SongArtist.create(song_id: s13.id, artist_id: a8.id)
SongArtist.create(song_id: s14.id, artist_id: a8.id)
SongArtist.create(song_id: s15.id, artist_id: a8.id)
SongArtist.create(song_id: s16.id, artist_id: a9.id)
SongArtist.create(song_id: s17.id, artist_id: a9.id)
SongArtist.create(song_id: s18.id, artist_id: a9.id)
SongArtist.create(song_id: s19.id, artist_id: a9.id)
SongArtist.create(song_id: s20.id, artist_id: a9.id)
SongArtist.create(song_id: s21.id, artist_id: a10.id)
SongArtist.create(song_id: s22.id, artist_id: a10.id)
SongArtist.create(song_id: s23.id, artist_id: a10.id)
SongArtist.create(song_id: s24.id, artist_id: a10.id)
SongArtist.create(song_id: s25.id, artist_id: a10.id)
SongArtist.create(song_id: s26.id, artist_id: a10.id)
SongArtist.create(song_id: s27.id, artist_id: a10.id)
SongArtist.create(song_id: s28.id, artist_id: a11.id)
SongArtist.create(song_id: s29.id, artist_id: a2.id)
SongArtist.create(song_id: s30.id, artist_id: a12.id)
SongArtist.create(song_id: s31.id, artist_id: a12.id)
SongArtist.create(song_id: s32.id, artist_id: a12.id)

Review.create(song_id:s1.id, user_id:u1.id, content:"Classic. Timeless.", rating:5)
Review.create(song_id: s5.id, user_id: u3.id, content: "I just found out about his artist. Not super impressed with their work." , rating: 2)
Review.create(song_id: s3.id, user_id: u2.id, content: "This shit Lit!" , rating: 4)
Review.create(song_id: s32.id, user_id: u4.id,content: "Legend says they still don’t know if someone opens the window." , rating: 4)
Review.create(song_id: s21.id, user_id: u1.id,content: "This could be us but we broke" , rating: 2)
Review.create(song_id: s14.id, user_id: u2.id,content: "Artist genius at work." , rating: 4)
Review.create(song_id: s15.id, user_id: u1.id,content: "Wow. Cant feel my face anymore." , rating: 5)
Review.create(song_id: s15.id, user_id: u2.id,content: "Everyone makes fun of his hair... yall just jealous because he doesnt need an unbrella when it rains." , rating: 5)
Review.create(song_id: s15.id, user_id: u2.id,content: "I wish there was a way to get that 3 minutes back. Wow, that was horrible." , rating: 2)
Review.create(song_id: s15.id, user_id: u3.id,content: "I was expecting more from him. Not buying the album." , rating: 3)
Review.create(song_id: s16.id, user_id: u2.id,content: "Imagine if he was alive." , rating: 5)
Review.create(song_id: s11.id, user_id: u4.id,content: "Woke AF" , rating: 4)
Review.create(song_id: s13.id, user_id: u3.id,content: "When I hear the Weeknd, I hear a shinning star" , rating: 3)
Review.create(song_id: s18.id, user_id: u2.id,content: "Wig snatched." , rating: 5)
Review.create(song_id: s18.id, user_id: u1.id,content: "Incredible atrist. Incredible Work. Forever a jam!" , rating: 5)
Review.create(song_id: s19.id, user_id: u2.id,content: "I can never not dance to this. Incredible." , rating: 5)
Review.create(song_id: s19.id, user_id: u1.id,content: "On repeat since I first heard it! " , rating: 5)
Review.create(song_id: s13.id, user_id: u2.id,content: "How does he do this! Take my money!" , rating: 5)
Review.create(song_id: s12.id, user_id: u3.id,content: "This my shit!" , rating: 5)

puts "we be seeded"